version: 2.1
jobs:
  build:
    docker:
       - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Hello World!"
workflows:
  default:
    jobs:
      - build


