version: 2.1
jobs:
  build:
    docker:
       - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Hello World!"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run : echo ${CIRCLE_WORKFLOW_ID}
workflows:
  default:
    jobs:
      - build
      - test


